### ISSUE TITLE
Support for non-standard WebRoot?

### ISSUE THREAD

**Issue by Aumnia** [RendleLabs/dotnet-unpkg#2]
Hi,

I've started using ```public``` instead of ```webroot``` in my recent MVC projects by updating my Program.cs:
>  public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseWebRoot("public")
                .UseStartup<Startup>()
                .Build();

A temporary workaround with unpkg CLI is to just move the files and edit the unpkg.json, then restore works during deployment.

What do you think about having support for this?

Thanks

**Comment by ThatRendle** [comment]
I was wondering whether people might want support for this. Will add to the next version.

Options for configuring the folder:

1. Command-line flag, e.g. `--webroot=public`
2. `.unpkg` file with setting in JSON
3. Environment variable, e.g. `UNPKG_WEBROOT`
4. All of the above.

Any preference?

**Comment by Aumnia** [comment]
Command-line would be sufficient as I ended up putting a *PostBuild* Command in my .csproj to do the restore in Azure and I can just add the ```--webroot=public``` to that.  Thanks!

**Comment by ThatRendle** [comment]
OK, I just pushed 1.4 to NuGet, using standard .NET Core configuration so `--wwwroot=public` will work, e.g.

```
$ dotnet unpkg add --wwwroot=public jquery
```

**Comment by Aumnia** [comment]
Upgraded and tried it out, works perfectly, thanks!
